spring:
  datasource:
    url: jdbc:mysql://host.docker.internal:3306/users
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    generate-ddl: true
    database-platform: org.hibernate.dialect.MySQL8Dialect
  application:
    name: timeline
  config:
    import: optional:configserver:http://localhost:8888

  cloud:
    stream:
      kafka:
        binders:
          brokers: localhost:9092
      bindings:
        consumer-in-0:
          destination: created

logging:
  level:
    org.hibernate.SQL: debug

management:
  endpoints:
    web:
      exposure:
        include: '*'

server.port: 8002